/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import Home.HomeFrame;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        HomeFrame classUnderTest = new HomeFrame();
    }
}
